name: "NX-584"
description: "Interface to GE/CaddX/NetworkX alarm systems via NX-584/NX8E"
version: "1.0.5"
slug: "nx584"
init: false
uart: true
map:
 - "config:rw"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5007/tcp: 5007
options:
  serial:
   enabled: true
   device: "/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0"
   baud: "9600"
  socat:
   enabled: false
   host: "192.168.30.1"
   port: "10000"
  config:
   max_zone: "4"
   zone_name_update: false
   euro_date_format: true
   use_binary_protocol: false
   idle_time_heartbeat_seconds: "120"
   zones: "NX Main entrance,NX Kitchen,NX Despacho,NX Garage"
  debug_enabled: false
schema:
  serial:
   enabled: "bool"
   device: "str"
   baud: "str"
  socat:
   enabled: "bool"
   host: "str"
   port: "str" 
  config:
   max_zone: "str"
   zone_name_update: "bool"
   euro_date_format: "bool"
   use_binary_protocol: "bool"
   idle_time_heartbeat_seconds: "str"
   zones: "str"
  debug_enabled: "bool"
